__default__:
  ntasks: 1
  ncpupertask: 1
  mem: 5M
  time: 1440

ccs:
  ntasks: 1
  ncpupertask: 50
  time: 2880

align_ccs:
  ntasks: 1
  ncpupertask: 20
  time: 1440

align_nonccs:
  ntasks: 1
  ncpupertask: 20
  time: 1440

sample_check:
  ntasks: 1
  ncpupertask: 8
  time: 2200

primrose:
  ntasks: 1
  ncpupertask: 20
  time: 1440

align_ccs_chm13:
  ntasks: 1
  ncpupertask: 20
  time: 1440

align_nonccs_chm13:
  ntasks: 1
  ncpupertask: 20
  time: 1440

dcache_copy:
  ntasks: 1
  ncpupertask: 1
  time: 1440

md5_check:
  ntasks: 1
  ncpupertask: 1
  time: 1440

coverage_summary:
  ntasks: 1
  ncpupertask: 1
  time: 600

extract_ccs_deepcons:
  ntasks: 1
  ncpupertask: 1
  time: 600

align_ccs_subreads_deepcons:
  ntasks: 1
  ncpupertask: 20
  time: 1440

deepconsensus_run:
  ntasks: 1
  ncpupertask: 20
  time: 1440

demultiplexing:
  ntasks: 1
  ncpupertask: 6
  time: 1440

read_length_distr:
  ntasks: 1
  ncpupertask: 2
  time: 600
