__default__:
  ntasks: 1
  ncpupertask: 1
  mem: 5M

ccs:
  ntasks: 1
  ncpupertask: 50

align_ccs:
  ntasks: 1
  ncpupertask: 50

align_sub:
  ntasks: 1
  ncpupertask: 50

sample_check:
  ntasks: 1
  ncpupertask: 12

primrose:
  ntasks: 1
  ncpupertask: 50

align_ccs_chm13:
  ntasks: 1
  ncpupertask: 50

align_nonccs_chm13:
  ntasks: 1
  ncpupertask: 50

dcache_copy:
  ntasks: 1
  ncpupertask: 1

md5_check:
  ntasks: 1
  ncpupertask: 1

coverage_summary:
  ntasks: 1
  ncpupertask: 1