__default__:
  ntasks: 1
  ncpupertask: 1
  mem: 5M

merge_hifi_hg38:
  ntasks: 1
  ncpupertask: 20

index_hifi_hg38:
  ntasks: 1
  ncpupertask: 4

merge_nonhifi_hg38:
  ntasks: 1
  ncpupertask: 20

index_nonhifi_hg38:
  ntasks: 1
  ncpupertask: 4

merge_hifi_chm13:
  ntasks: 1
  ncpupertask: 20

index_hifi_chm13:
  ntasks: 1
  ncpupertask: 4

merge_nonhifi_chm13:
  ntasks: 1
  ncpupertask: 20

index_nonhifi_chm13:
  ntasks: 1
  ncpupertask: 4

pileup_analysis_hg38:
  ntasks: 1
  ncpupertask: 50

pileup_analysis_chm13:
  ntasks: 1
  ncpupertask: 50

deepvariant_hg38:
  ntasks: 1
  ncpupertask: 60

deepvariant_chm13:
  ntasks: 1
  ncpupertask: 60

bam2fasta:
  ntasks: 1
  ncpupertask: 10

hifiasm_phased:
  ntasks: 1
  ncpupertask: 40

hifiasm_primary:
  ntasks: 1
  ncpupertask: 40

gfa2fasta:
  ntasks: 1
  ncpupertask: 1

align_hifiasm_hg38:
  ntasks: 1
  ncpupertask: 40

align_hifiasm_chm13:
  ntasks: 1
  ncpupertask: 40

busco_analysis:
  ntasks: 1
  ncpupertask: 20

flye_assembly:
  ntasks: 1
  ncpupertask: 40

align_flye:
  ntasks: 1
  ncpupertask: 40

busco_flye:
  ntasks: 1
  ncpupertask: 20

sv_discover_pbsv_reads:
  ntasks: 1
  ncpupertask: 2

sv_call_pbsv_reads:
  ntasks: 1
  ncpupertask: 10

sv_call_sniffles_reads:
  ntasks: 1
  ncpupertask: 10
